module.exports=function(e){var t={};function n(o){if(t[o])return t[o].exports;var r=t[o]={i:o,l:!1,exports:{}};return e[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}return n.m=e,n.c=t,n.d=function(e,t,o){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)n.d(o,r,function(t){return e[t]}.bind(null,r));return o},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./index.js")}({"./index.js":
/*!******************!*\
  !*** ./index.js ***!
  \******************/
/*! exports provided: loginFunction, signupFunction, validateTokenFunction, generateCodeFunction, validateCodeFunction, isAliveFunction */function(e,t,n){"use strict";n.r(t),n.d(t,"loginFunction",function(){return i}),n.d(t,"signupFunction",function(){return c}),n.d(t,"validateTokenFunction",function(){return d}),n.d(t,"generateCodeFunction",function(){return l}),n.d(t,"validateCodeFunction",function(){return u}),n.d(t,"isAliveFunction",function(){return f});var o=n(/*! ./src/controllers/user/login */"./src/controllers/user/login.js"),r=n(/*! ./src/controllers/user/signup */"./src/controllers/user/signup.js"),s=n(/*! ./src/controllers/user/validateToken */"./src/controllers/user/validateToken.js"),a=n(/*! ./src/controllers/user/phone */"./src/controllers/user/phone.js");const i=o.login,c=r.signup,d=s.validateToken,l=a.generateCode,u=a.validateCode,f=()=>({statusCode:200,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({})})},"./src/controllers/user/login.js":
/*!***************************************!*\
  !*** ./src/controllers/user/login.js ***!
  \***************************************/
/*! exports provided: login, default */function(e,t,n){"use strict";n.r(t),n.d(t,"login",function(){return f});var o=n(/*! bcrypt */"bcrypt"),r=n.n(o),s=n(/*! jsonwebtoken */"jsonwebtoken"),a=n.n(s),i=n(/*! dotenv */"dotenv"),c=n.n(i),d=n(/*! ../../status */"./src/status.js"),l=n(/*! ../../db/Mongodb */"./src/db/Mongodb.js");c.a.config();let u=null;const f=async e=>{const{username:t,password:n}=JSON.parse(e.body),{SECRET:o,MONGO_URL:s}=e.stageVariables||{SECRET:"weednaoehganja",MONGO_URL:process.env.MONGO_URL};try{const e=(u=await Object(l.default)({conn:u,mongoUrl:s})).model("users"),i=await e.findOne({username:t});if(!i)return{status:d.default.UNAUTHORIZED.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({error:"user/not-found"})};if(!await r.a.compare(n,i.password))return{statusCode:d.default.UNAUTHORIZED.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({error:"user/wrong-password"})};const c=a.a.sign({username:t,ida:i._id},o,{expiresIn:"1h"});return{statusCode:d.default.ACCEPTED.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({data:{ida:i._id,token:c}})}}catch(e){return{statusCode:d.default.INTERNAL_SERVER_ERROR.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({error:e})}}};t.default=f},"./src/controllers/user/phone.js":
/*!***************************************!*\
  !*** ./src/controllers/user/phone.js ***!
  \***************************************/
/*! exports provided: generateCode, validateCode */function(e,t,n){"use strict";n.r(t),n.d(t,"generateCode",function(){return l}),n.d(t,"validateCode",function(){return u});var o=n(/*! aws-sdk */"aws-sdk"),r=n.n(o),s=n(/*! ../../db/Mongodb */"./src/db/Mongodb.js"),a=n(/*! ../../status */"./src/status.js");r.a.config.region="us-west-2";let i=null;const c={"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},d=()=>{let e="";for(let t=0;t<6;t+=1)e+=0===t?"123456789".charAt(Math.floor(Math.random()*"123456789".length)):"0123456789".charAt(Math.floor(Math.random()*"0123456789".length));return e},l=async e=>{const{phone:t,ida:n}=JSON.parse(e.body);let o=/^\+[0-9]{13}$/.test(t);if(!o)return{statusCode:a.default.BAD_REQUEST.code,headers:c,body:JSON.stringify({error:"phone/invalid-number"})};if(o=/^[0-9a-fA-F]{24}$/.test(n),console.log("heree",o,n),!o)return{statusCode:a.default.BAD_REQUEST.code,headers:c,body:JSON.stringify({error:"phone/invalid-ida"})};const l={phone:{number:t,valid:!1,confirmation_code:d()}},{MONGO_URL:u}=e.stageVariables||{MONGO_URL:process.env.MONGO_URL},f=(i=await Object(s.default)({conn:i,mongoUrl:u})).model("users");let p;try{p=await f.findOneAndUpdate({_id:n},l,{new:!0})}catch(e){return{statusCode:a.default.INTERNAL_SERVER_ERROR.code,headers:c,body:JSON.stringify({error:e})}}if(console.log("heree 2",p),!p)return{statusCode:a.default.BAD_REQUEST.code,headers:c,body:JSON.stringify({error:"phone/invalid-ida"})};const g=new r.a.SNS,y={Message:`IDA-${l.phone.confirmation_code} é o código de confirmação de seu telefone para sua conta no SOM/IDA.`,MessageStructure:"string",PhoneNumber:t},C=await g.publish(y),O=await C.send();return O.error?{statusCode:a.default.INTERNAL_SERVER_ERROR.code,headers:c,body:JSON.stringify({error:O.error})}:{statusCode:a.default.SUCCESS.code,headers:c,body:JSON.stringify({data:{ida:p._id,phone:{number:t,valid:!1}}})}},u=async()=>{}},"./src/controllers/user/signup.js":
/*!****************************************!*\
  !*** ./src/controllers/user/signup.js ***!
  \****************************************/
/*! exports provided: signup, default */function(e,t,n){"use strict";n.r(t),n.d(t,"signup",function(){return u});var o=n(/*! dotenv */"dotenv"),r=n.n(o),s=n(/*! jsonwebtoken */"jsonwebtoken"),a=n.n(s),i=n(/*! ../utils */"./src/controllers/utils.js"),c=n(/*! ../../db/Mongodb */"./src/db/Mongodb.js"),d=n(/*! ../../status */"./src/status.js");r.a.config();let l=null;const u=async e=>{const{username:t,password:n}=JSON.parse(e.body),{SECRET:o,MONGO_URL:r}=e.stageVariables||{SECRET:"weednaoehganja",MONGO_URL:process.env.MONGO_URL};try{const e=(l=await Object(c.default)({conn:l,mongoUrl:r})).model("users");if(await e.findOne({username:t}))return{statusCode:d.default.UNAUTHORIZED.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({error:"auth/duplicated-user"})};const s=new e({username:t,password:await Object(i.hashPassword)(n)});await s.save();const u=a.a.sign({username:t,ida:s._id},o,{expiresIn:"1h"});return{statusCode:d.default.CREATED.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({data:{ida:s._id,token:u}})}}catch(e){return{statusCode:d.default.INTERNAL_SERVER_ERROR.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({error:e})}}};t.default=u},"./src/controllers/user/validateToken.js":
/*!***********************************************!*\
  !*** ./src/controllers/user/validateToken.js ***!
  \***********************************************/
/*! exports provided: validateToken, default */function(e,t,n){"use strict";n.r(t),n.d(t,"validateToken",function(){return c});var o=n(/*! jsonwebtoken */"jsonwebtoken"),r=n.n(o),s=n(/*! dotenv */"dotenv"),a=n.n(s),i=n(/*! ../../status */"./src/status.js");a.a.config();const c=async e=>{const{token:t}=JSON.parse(e.body),{SECRET:n}=e.stageVariables||{SECRET:"weednaoehganja"};try{const e=await r.a.verify(t,n);return{statusCode:200,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify(e)}}catch(e){return{statusCode:i.default.UNAUTHORIZED.code,headers:{"Access-Control-Allow-Credentials":!0,"Access-Control-Allow-Origin":"*","Content-Type":"application/json"},body:JSON.stringify({error:i.default.UNAUTHORIZED.tag})}}};t.default=c},"./src/controllers/utils.js":
/*!**********************************!*\
  !*** ./src/controllers/utils.js ***!
  \**********************************/
/*! exports provided: hashPassword, default */function(e,t,n){"use strict";n.r(t),n.d(t,"hashPassword",function(){return s});var o=n(/*! bcrypt */"bcrypt"),r=n.n(o);const s=async e=>{return await new Promise((t,n)=>{r.a.hash(e,10,(e,o)=>{e&&n(e),t(o)})})};t.default=s},"./src/db/Mongodb.js":
/*!***************************!*\
  !*** ./src/db/Mongodb.js ***!
  \***************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t);var o=n(/*! mongoose */"mongoose"),r=n.n(o),s=n(/*! ./models/users.model */"./src/db/models/users.model.js");r.a.Promise=global.Promise,t.default=async({conn:e,mongoUrl:t="mongodb://localhost/auth-ida"})=>{try{if(!e){console.log("=> using new database connection"),r.a.model("users",s.default);const e=await r.a.createConnection(t,{bufferCommands:!1,bufferMaxEntries:0,keepAlive:!0});return e.model("users",s.default),e}return console.log("=> using existing database connection"),e}catch(e){throw e}}},"./src/db/models/users.model.js":
/*!**************************************!*\
  !*** ./src/db/models/users.model.js ***!
  \**************************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t);var o=n(/*! mongoose */"mongoose");const r=new o.Schema({username:{type:String,unique:!0,required:!0},password:{type:String,required:!0},active:{type:Boolean,default:!0},email:{address:{type:String,required:!0},valid:{type:Boolean,default:!1}},phone:[{number:{type:String,required:!0},valid:{type:Boolean,default:!1},confirmation_code:{type:String,required:!0}}],last_login:{type:Date,default:Date.now()}},{usePushEach:!0,timestamps:{updatedAt:"updated_at",createdAt:"created_at"}});t.default=r},"./src/status.js":
/*!***********************!*\
  !*** ./src/status.js ***!
  \***********************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t),t.default={SUCCESS:{code:200,tag:"success"},CREATED:{code:201,tag:"register"},ACCEPTED:{code:202,tag:"accepted"},BAD_REQUEST:{code:400,tag:"bad-request"},UNAUTHORIZED:{code:401,tag:"unauthorized"},INTERNAL_SERVER_ERROR:{code:500,tag:"internal-server-error"}}},"aws-sdk":
/*!**************************!*\
  !*** external "aws-sdk" ***!
  \**************************/
/*! no static exports found */function(e,t){e.exports=require("aws-sdk")},bcrypt:
/*!*************************!*\
  !*** external "bcrypt" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("bcrypt")},dotenv:
/*!*************************!*\
  !*** external "dotenv" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("dotenv")},jsonwebtoken:
/*!*******************************!*\
  !*** external "jsonwebtoken" ***!
  \*******************************/
/*! no static exports found */function(e,t){e.exports=require("jsonwebtoken")},mongoose:
/*!***************************!*\
  !*** external "mongoose" ***!
  \***************************/
/*! no static exports found */function(e,t){e.exports=require("mongoose")}});
//# sourceMappingURL=index.js.map